package com.capitalone.creditocr.model.dao;

import com.capitalone.creditocr.model.dto.document_image.DocumentImage;
import com.capitalone.creditocr.model.dto.job.ProcessingJob;

import java.util.Optional;

/**
 * DAO interface for {@link DocumentImage}
 */
public interface DocumentImageDao {


    /**
     * This method adds a new page to the document_images table. Additionally, a job will be created for the
     * image to be processed by an image processing worker. The {@link DocumentImage#getId()} field will be updated
     * with the unique ID generated by the database.
     * @param document the document to be uploaded
     *
     */
    void addNewImage(DocumentImage document);

    /**
     * Get the image associated with a job in the job queue
     * @param id the job
     * @return the related image, if it exists
     */
    Optional<DocumentImage> getImageForJob(ProcessingJob id);

    /**
     * Get the image associated with a specific document page
     * @param documentId the primary key of the relevant document
     * @param page the requested page
     * @return The requested image, if it exists
     */
    Optional<DocumentImage> getImageForDocument(int documentId, int page);

    /**
     * Get the image associated with a document's envelope, if it exists
     * @param id the document ID
     * @return The requested image, if it exists.
     */
    Optional<DocumentImage> getEnvelopeForDocument(int id);
}
