package com.capitalone.creditocr.model.dao;

import com.capitalone.creditocr.model.dto.document.Document;
import com.capitalone.creditocr.model.dto.document.PostalAddress;

import java.util.List;
import java.util.Optional;


public interface DocumentDao {

    /**
     * This method will insert a document into the database. The {@link Document#id} field will also be
     * set with the unique ID that was automatically generated by the database.
     * @param document The document to insert.
     */
    void createDocument(Document document);

    int getDocumentIDbyJob(int id);

    /**
     * Get a document by the document id
     * @param id the id
     * @return the document
     */
    Optional<Document> getDocumentById(int id);

    /**
     * List document IDs which are substantially similar to a document given a simhash fingerprint
     * @param fingerprint The simhash fingerprint of the document to compare
     * @param sensitivity The minimum percent similarity between the given hash and the hash of a document to include in the result set. Range = [0, 1], inclusive
     * @return The set of document IDs which are similar to the given fingerprint
     */
    List<Integer> getSimilarDocumentIds(byte[] fingerprint, float sensitivity);

    void updateDocument(Document document);

    /**
     * Set address for document
     * @param documentId the document id to attach the address to
     * @param address the address
     */
    void setAddress(int documentId, PostalAddress address);
}
