package com.capitalone.creditocr.model.dao;

import com.capitalone.creditocr.model.dto.document_image.DocumentImageDto;

/**
 * DAO interface for {@link DocumentImageDto}
 */
public interface DocumentImageDao {


    /**
     * This method adds a new page to the document_images table. Additionally, a job will be created for the
     * image to be processed by an image processing worker. The {@link DocumentImageDto#id} field will be updated
     * with the unique ID generated by the database.
     * @param document the document to be uploaded
     *
     */
    void addNewImage(DocumentImageDto document);

}
